apiVersion: v1
kind: Service
metadata:
  name: todoapp-nodeport
  namespace: mateapp
  labels:
    app: todoapp
spec:
  type: NodePort
  selector:
    app: todoapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      name: http # Додано назву порту